#!/usr/bin/env python3

"""Script to create a new directory and README"""

import os
import glob

import termcolor
import vimbuffer

os.environ["VIMBUFFER_EDITOR"] = "nvim"

# cd into the root dir
os.chdir(os.path.dirname(os.path.abspath(__file__))) 

prob_number = int(input("Problem Number: "))

# get language name from user
language_name = input("Language Name (for folder)? ")

new_dir_path = "{}-{}".format(str(prob_number).zfill(3), language_name)

# confirm directory
override = input("Hit enter to confirm '{}' or type in an alternative: ".format(termcolor.colored(new_dir_path, "green"))).strip()

# if overriden, save that
if override:
    new_dir_path = override

# language version for readme
language_ver = input("Language name + version? ").strip()

# create dir
os.mkdir(new_dir_path)

# crate Makefile

with open(f"{new_dir_path}/Makefile", 'w') as makefile:
    makefile.write("run:\n")

README_STR = f"""## [Problem {prob_number}](https://projecteuler.net/problem={prob_number})

Language: {language_ver}

##### Requires

- [``]()"""

with open(f"{new_dir_path}/README.md", 'w') as readme:
    readme.write(vimbuffer.buffer(string=README_STR))

print("Done!")
